# Generated by Django 2.1.11 on 2021-09-17 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Dashboard', '0004_auto_20210917_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxiCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to='profile_pics')),
                ('company_details', models.CharField(max_length=264)),
                ('url', models.CharField(max_length=264)),
                ('address', models.CharField(max_length=264)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Deactivate')])),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Dashboard.Country')),
            ],
        ),
    ]
